# Generated by Django 4.1.13 on 2025-07-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wage',
            table='wages',
        ),
    ]
