# Generated by Django 4.1.13 on 2025-06-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
