# Generated by Django 4.1.13 on 2025-06-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
