# Generated by Django 4.1.13 on 2025-07-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0002_alter_wage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wage',
            table='xe_wages',
        ),
    ]
