# Generated by Django 4.1.13 on 2025-06-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0003_alter_employee_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract'), ('Others', 'Others')], max_length=100),
        ),
    ]
