# Generated by Django 4.1.13 on 2025-08-01 08:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0003_alter_wage_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Attendance Date')),
                ('total_employees_present', models.PositiveIntegerField(default=0, verbose_name='Total Present')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Daily Remarks')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Wages Calculated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendances',
                'db_table': 'xe_attendance',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='EmployeeWageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Period')], default='weekly', max_length=20)),
                ('period_start', models.DateField(verbose_name='Period Start Date')),
                ('period_end', models.DateField(verbose_name='Period End Date')),
                ('total_days_present', models.PositiveIntegerField(default=0)),
                ('total_days_absent', models.PositiveIntegerField(default=0)),
                ('total_half_days', models.PositiveIntegerField(default=0)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_wage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total Wage Amount')),
                ('total_overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total Overtime Amount')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bonus Amount')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Deductions')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gross Amount')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Net Payable Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Amount Paid')),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pending Amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Summary Processed')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_summaries', to='xe_farm.employee')),
            ],
            options={
                'verbose_name': 'Employee Wage Summary',
                'verbose_name_plural': 'Employee Wage Summaries',
                'db_table': 'xe_employee_wage_summary',
                'ordering': ['-period_end', 'employee__name'],
                'unique_together': {('employee', 'period_start', 'period_end')},
            },
        ),
        migrations.RenameField(
            model_name='wage',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.CreateModel(
            name='WagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Payment Amount')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('card', 'Card')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference/Transaction ID')),
                ('paid_by', models.CharField(max_length=255, verbose_name='Paid By')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Receipt/Proof URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wage_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='xe_farm.employeewagesummary')),
            ],
            options={
                'verbose_name': 'Wage Payment',
                'verbose_name_plural': 'Wage Payments',
                'db_table': 'xe_wage_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('overtime', 'Overtime'), ('leave', 'Leave')], max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Hours Worked')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Overtime Hours')),
                ('daily_wage_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Daily Wage Earned')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Overtime Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total Amount Earned')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='xe_farm.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='xe_farm.employee')),
            ],
            options={
                'verbose_name': 'Employee Attendance',
                'verbose_name_plural': 'Employee Attendances',
                'db_table': 'xe_employee_attendance',
                'ordering': ['-attendance__date', 'employee__name'],
                'unique_together': {('attendance', 'employee')},
            },
        ),
    ]
