# Generated by Django 4.1.13 on 2025-06-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0005_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255, verbose_name='Farm Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farm Segment',
                'verbose_name_plural': 'Farm Segments',
                'db_table': 'farm_segments',
                'ordering': ['-created_at'],
            },
        ),
    ]
