# Generated by Django 4.1.13 on 2025-06-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0007_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variant', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Bunch', 'Bunch'), ('Pack', 'Pack')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='xe_farm.crop')),
            ],
            options={
                'db_table': 'xe_crop_variants',
                'unique_together': {('crop', 'crop_variant')},
            },
        ),
    ]
