# Generated by Django 4.1.13 on 2025-06-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0008_cropvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateTimeField()),
                ('bill_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='xe_farm.crop')),
            ],
            options={
                'verbose_name': 'Yield',
                'verbose_name_plural': 'Yields',
                'db_table': 'xe_yields',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YieldVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_variants', to='xe_farm.cropvariant')),
                ('yield_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_variants', to='xe_farm.yield')),
            ],
            options={
                'db_table': 'xe_yield_variants',
                'unique_together': {('yield_record', 'crop_variant')},
            },
        ),
        migrations.CreateModel(
            name='YieldFarmSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_farm_segments', to='xe_farm.farmsegment')),
                ('yield_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_farm_segments', to='xe_farm.yield')),
            ],
            options={
                'db_table': 'xe_yield_farm_segments',
                'unique_together': {('yield_record', 'farm_segment')},
            },
        ),
    ]
