# Generated by Django 4.1.13 on 2025-06-23 08:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0010_sale_salevariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255, verbose_name='Job Name')),
                ('job_date', models.DateField(verbose_name='Job Date')),
                ('job_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('no_of_employees', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'xe_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFarmSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_farm_segments', to='xe_farm.farmsegment')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_farm_segments', to='xe_farm.job')),
            ],
            options={
                'db_table': 'xe_job_farm_segments',
                'unique_together': {('job', 'farm_segment')},
            },
        ),
        migrations.CreateModel(
            name='JobEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_employees', to='xe_farm.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_employees', to='xe_farm.job')),
            ],
            options={
                'db_table': 'xe_job_employees',
                'unique_together': {('job', 'employee')},
            },
        ),
    ]
