# Generated by Django 4.1.13 on 2025-06-23 11:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0011_job_jobfarmsegment_jobemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Shopping', 'Shopping'), ('Utilities', 'Utilities'), ('Education', 'Education'), ('Travel', 'Travel'), ('Others', 'Others')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('spent_by', models.CharField(max_length=255)),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Wallet', 'Wallet'), ('Others', 'Others')], max_length=100)),
                ('expense_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xe_expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
