# Generated by Django 4.1.13 on 2025-08-06 13:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(unique=True, verbose_name='Week Start Date')),
                ('week_end_date', models.DateField(verbose_name='Week End Date')),
                ('total_employees', models.IntegerField(default=0, verbose_name='Total Employees')),
                ('total_present_days', models.IntegerField(default=0, verbose_name='Total Present Days (Sum)')),
                ('total_half_days', models.IntegerField(default=0, verbose_name='Total Half Days (Sum)')),
                ('total_gross_wages', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Gross Wages')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Deductions')),
                ('total_net_wages', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Net Wages')),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Paid Amount')),
                ('total_pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Pending Amount')),
                ('is_wages_paid', models.BooleanField(default=False, verbose_name='All Wages Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly Attendance Summary',
                'verbose_name_plural': 'Weekly Attendance Summaries',
                'db_table': 'xe_attendance_weekly_summary',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255, verbose_name='Crop Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'db_table': 'xe_crops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variant', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Bunch', 'Bunch'), ('Pack', 'Pack')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='xe_farm.crop')),
            ],
            options={
                'db_table': 'xe_crop_variants',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tamil_name', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('emp_type', models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract'), ('Others', 'Others')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xe_employee',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Advance', 'Advance'), ('Food', 'Food'), ('Transport', 'Transport'), ('Donation and Give Away', 'Donation and Give Away'), ('Driver', 'Driver'), ('Miscellinious', 'Miscellinious'), ('Machine and Motor Repairs', 'Machine and Motor Repairs'), ('Jeep Maintenance', 'Jeep Maintenance'), ('Eb/Phone/Admin Exp', 'Eb/Phone/Admin Exp'), ('Fuel', 'Fuel'), ('Tree Samplings', 'Tree Samplings'), ('Farm Maintenance', 'Farm Maintenance'), ('Weekly Wages', 'Weekly Wages')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('spent_by', models.CharField(max_length=255)),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], max_length=100)),
                ('expense_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xe_expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255, verbose_name='Farm Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farm Segment',
                'verbose_name_plural': 'Farm Segments',
                'db_table': 'farm_segments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255, verbose_name='Job Name')),
                ('job_date', models.DateField(verbose_name='Job Date')),
                ('job_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('no_of_employees', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'xe_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('payment_terms', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Online', 'Online')], max_length=100)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xe_merchant',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Online', 'Online')], max_length=20)),
                ('harvest_date', models.DateTimeField()),
                ('bill_url', models.URLField(blank=True, max_length=500, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lorry_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cooly_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='xe_farm.merchant')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'xe_sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateTimeField()),
                ('bill_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='xe_farm.crop')),
            ],
            options={
                'verbose_name': 'Yield',
                'verbose_name_plural': 'Yields',
                'db_table': 'xe_yields',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyWagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='Week Start Date')),
                ('week_end_date', models.DateField(verbose_name='Week End Date')),
                ('employee_name', models.CharField(default='Unknown', help_text='Cached employee name', max_length=255, verbose_name='Employee Name')),
                ('total_present_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Present Days')),
                ('total_half_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Half Days')),
                ('daily_wage_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Wage Amount')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gross Amount')),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Advance Deduction')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Other Deductions')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Deductions')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Net Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount Paid')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Remaining Amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Reference')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Payment Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_wage_payments', to='xe_farm.employee')),
                ('expense_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_payment', to='xe_farm.expense', verbose_name='Associated Expense Entry')),
            ],
            options={
                'verbose_name': 'Weekly Wage Payment',
                'verbose_name_plural': 'Weekly Wage Payments',
                'db_table': 'xe_weekly_wage_payments',
                'ordering': ['-week_start_date', 'employee_name'],
            },
        ),
        migrations.CreateModel(
            name='WagePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wage_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='xe_farm.weeklywagepayment')),
            ],
            options={
                'verbose_name': 'Wage Payment Transaction',
                'verbose_name_plural': 'Wage Payment Transactions',
                'db_table': 'xe_wage_payment_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Wage Amount')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wages', to='xe_farm.employee')),
            ],
            options={
                'verbose_name': 'Wage',
                'verbose_name_plural': 'Wages',
                'db_table': 'xe_wages',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_variants', to='xe_farm.cropvariant')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_variants', to='xe_farm.sale')),
            ],
            options={
                'db_table': 'xe_sale_variants',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='yield_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='xe_farm.yield'),
        ),
        migrations.CreateModel(
            name='JobFarmSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_farm_segments', to='xe_farm.farmsegment')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_farm_segments', to='xe_farm.job')),
            ],
            options={
                'db_table': 'xe_job_farm_segments',
            },
        ),
        migrations.CreateModel(
            name='JobEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_employees', to='xe_farm.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_employees', to='xe_farm.job')),
            ],
            options={
                'db_table': 'xe_job_employees',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Attendance Date')),
                ('attendance_data', models.JSONField(default=list, help_text='Array of employee attendance records', verbose_name='Attendance Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_records', to='xe_farm.employee', verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'xe_attendance_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='YieldVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_variants', to='xe_farm.cropvariant')),
                ('yield_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_variants', to='xe_farm.yield')),
            ],
            options={
                'db_table': 'xe_yield_variants',
                'unique_together': {('yield_record', 'crop_variant')},
            },
        ),
        migrations.CreateModel(
            name='YieldFarmSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_farm_segments', to='xe_farm.farmsegment')),
                ('yield_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_farm_segments', to='xe_farm.yield')),
            ],
            options={
                'db_table': 'xe_yield_farm_segments',
                'unique_together': {('yield_record', 'farm_segment')},
            },
        ),
        migrations.AddConstraint(
            model_name='weeklywagepayment',
            constraint=models.UniqueConstraint(fields=('week_start_date', 'employee'), name='unique_employee_weekly_payment'),
        ),
        migrations.AddConstraint(
            model_name='wage',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='wage_effective_to_gte_effective_from'),
        ),
        migrations.AlterUniqueTogether(
            name='salevariant',
            unique_together={('sale', 'crop_variant')},
        ),
        migrations.AlterUniqueTogether(
            name='jobfarmsegment',
            unique_together={('job', 'farm_segment')},
        ),
        migrations.AlterUniqueTogether(
            name='jobemployee',
            unique_together={('job', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='cropvariant',
            unique_together={('crop', 'crop_variant')},
        ),
    ]
