# Generated by Django 4.1.13 on 2025-08-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkWagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('employee_payments', models.JSONField(default=list)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Card', 'Card')], default='Cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('expense_category', models.CharField(default='Wages', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xe_farm.employee')),
            ],
            options={
                'db_table': 'bulk_wage_payments',
                'unique_together': {('week_start_date', 'week_end_date')},
            },
        ),
    ]
