# Generated by Django 5.2.5 on 2025-08-20 06:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0002_bulkwagepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklywagepayment',
            options={'ordering': ['-week_start_date'], 'verbose_name': 'Weekly Wage Payment Record', 'verbose_name_plural': 'Weekly Wage Payment Records'},
        ),
        
        migrations.AlterModelTable(
            name='weeklywagepayment',
            table='xe_weekly_wage_payment_records',
        ),
    ]
