# Generated by Django 5.2.5 on 2025-08-20 07:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0003_alter_weeklywagepayment_options_and_more'),
    ]

    operations = [
       
    ]
