# Generated by Django 5.2.5 on 2025-08-20 07:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0004_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        
    ]
