# Generated by Django 5.2.5 on 2025-08-20 08:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0005_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        
        migrations.AlterModelTable(
            name='weeklywagepayment',
            table='xe_weekly_wage_payment',
        ),
    ]
