# Generated by Django 4.1.13 on 2025-08-30 12:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0009_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        
    ]
