# Generated by Django 4.1.13 on 2025-09-10 06:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0013_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='yield',
            name='bill_urls',
            field=models.JSONField(blank=True, default=list, help_text='Array of bill image URLs'),
        ),
        
    ]
