# Generated by Django 4.1.13 on 2025-09-15 05:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import xe_farm.models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0014_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        
        
        
       
        
        
    ]
