# Generated by Django 4.1.13 on 2025-09-15 07:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import xe_farm.models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0015_billimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to=xe_farm.models.bill_image_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xe_bill_images',
                'ordering': ['uploaded_at'],
            },
        ),
        
        
       
        
        
        
        
        
        
       
        
        
        
        migrations.AddField(
            model_name='billimage',
            name='yield_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_images', to='xe_farm.yield'),
        ),
    ]
