# Generated by Django 4.1.13 on 2025-09-17 06:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0016_billimage_and_more'),
    ]

    operations = [
        
    ]
