# Generated by Django 4.1.13 on 2025-09-23 05:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0018_paymenthistory_saleimage_and_more'),
    ]

    operations = [
        
    ]
