# Generated by Django 5.2.5 on 2025-10-23 09:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0019_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklywagepayment',
            name='unique_employee_weekly_payment',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='advance_deduction',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='daily_wage_amount',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='total_half_days',
        ),
        migrations.RemoveField(
            model_name='weeklywagepayment',
            name='total_present_days',
        ),
        migrations.RemoveField(
            model_name='yield',
            name='bill_url',
        ),
        migrations.RemoveField(
            model_name='yield',
            name='bill_urls',
        ),
        migrations.AddField(
            model_name='wagepaymenttransaction',
            name='employee_id',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='wagepaymenttransaction',
            name='employee_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='weeklywagepayment',
            name='employee_wages',
            field=models.JSONField(default=list, help_text='Array of employee wage objects with payment details', verbose_name='Employee Wage Data'),
        ),
        migrations.AddField(
            model_name='weeklywagepayment',
            name='total_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklywagepayment',
            name='total_gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='weeklywagepayment',
            name='total_net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='weeklywagepayment',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='weeklywagepayment',
            name='total_remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='spent_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weeklywagepayment',
            name='expense_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_wage_payment', to='xe_farm.expense', verbose_name='Associated Expense Entry'),
        ),
        migrations.AlterField(
            model_name='weeklywagepayment',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='weeklywagepayment',
            name='week_start_date',
            field=models.DateField(unique=True, verbose_name='Week Start Date'),
        ),
    ]
