# Generated by Django 5.2.5 on 2025-11-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0020_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('source_platform', models.CharField(max_length=100)),
                ('source_url', models.URLField(max_length=500)),
                ('event_name', models.CharField(max_length=500)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('event_category', models.CharField(blank=True, max_length=100, null=True)),
                ('event_format', models.CharField(blank=True, max_length=50, null=True)),
                ('event_status', models.CharField(default='Scheduled', max_length=50)),
                ('recurrence', models.CharField(blank=True, max_length=50, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_iso', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_open', models.DateTimeField(blank=True, null=True)),
                ('registration_close', models.DateTimeField(blank=True, null=True)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_capacity', models.IntegerField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('sponsors', models.JSONField(blank=True, default=list)),
                ('partners', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('organiser_name', models.CharField(blank=True, max_length=300, null=True)),
                ('organiser_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organiser_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organiser_location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('agenda_link', models.URLField(blank=True, max_length=500, null=True)),
                ('post_event_materials_link', models.URLField(blank=True, max_length=500, null=True)),
                ('expected_attendance', models.IntegerField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['start_datetime'], name='xe_farm_scr_start_d_ab0921_idx'), models.Index(fields=['city', 'country'], name='xe_farm_scr_city_fca1f0_idx'), models.Index(fields=['event_category'], name='xe_farm_scr_event_c_ffd0a5_idx')],
            },
        ),
    ]
