# Generated by Django 4.2.7 on 2025-12-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
