# Generated by Django 4.2.7 on 2025-12-15 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0002_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xe_farm.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xe_farm.jobs')),
            ],
        ),
    ]
