# Generated by Django 4.2.7 on 2025-12-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0003_jobassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
