# Generated by Django 4.2.7 on 2025-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0004_jobs_end_date_jobs_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignment',
            name='incomplete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('incompleted', 'Incompleted')], default='incompleted', max_length=100),
        ),
    ]
