# Generated by Django 4.2.7 on 2025-12-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0005_jobassignment_incomplete_reason_jobassignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobassignment',
            name='incomplete_reason',
        ),
        migrations.RemoveField(
            model_name='jobassignment',
            name='status',
        ),
        migrations.AddField(
            model_name='jobs',
            name='incomplete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('incompleted', 'Incompleted')], max_length=100, null=True),
        ),
    ]
