# Generated by Django 4.2.7 on 2025-12-15 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0006_remove_jobassignment_incomplete_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
