# Generated by Django 4.2.7 on 2025-12-15 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0007_alter_jobs_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 15, 11, 1, 12, 738288, tzinfo=datetime.timezone.utc)),
        ),
    ]
