# Generated by Django 4.2.7 on 2025-12-16 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0008_alter_jobs_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
