# Generated by Django 4.1.13 on 2025-09-06 07:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0011_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='crop',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Crop Image'),
        ),
        
    ]
