# Generated by Django 4.1.13 on 2025-09-09 14:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xe_farm', '0012_remove_weeklywagepayment_unique_employee_weekly_payment_and_more'),
    ]

    operations = [
        
    ]
